# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 16:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('station', models.CharField(blank=True, max_length=254, null=True)),
                ('site', models.CharField(blank=True, max_length=254, null=True)),
                ('img', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('yaw', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webcam',
                'managed': False,
            },
        ),
    ]
