"""
Django settings for djmapping project.

Generated by 'django-admin startproject' using Django 1.11.dev20160619004538.
This application runs on Django 1.8 and 1.9. geojson serialisation will not work with versions > 1.10

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
import pghm

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# This is application folder
APP_DIR = os.path.dirname(pghm.__file__)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS += [
    'django.contrib.gis',
    'leaflet',
    'djgeojson',    
    'pghm',
]

SERIALIZATION_MODULES = {
    'geojson': 'djgeojson.serializers'
}

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djmapping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djmapping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

SPATIALITE_LIBRARY_PATH = 'mod_spatialite'

DATABASES = {
    # 'default': {
    #     #'ENGINE': 'django.db.backends.sqlite3',
    #     'ENGINE': 'django.contrib.gis.db.backends.spatialite',
    #     'NAME': os.path.join(BASE_DIR, 'project.db.sqlite3'),
    # },
    #'default': {},
    'default': {
        #'ENGINE': 'django.db.backends.postgresql',
        #'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'ENGINE': 'django.contrib.gis.db.backends.postgis',        
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        #'HOST': '127.0.0.1',   # https://docs.djangoproject.com/en/dev/ref/settings/#host
        'HOST': '',             # defined by UNIX domain sockets (‘local’ lines in pg_hba.conf)
        'PORT': '',             # can be empty so the default postgresql port is used (5432)
    },
    # 'usersdb': {
    #     'ENGINE': 'django.contrib.gis.db.backends.postgis',        
    #     'NAME': 'usersdb',
    #     'USER': '',
    #     'PASSWORD': '',
    #     'HOST': '',
    #     'PORT': '',
    # }, 
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'


# Project particular settings

# IGN url generation & setup
# key
IGN_KEY = ''

# layer definition
IGN_LAYER = [
    'GEOGRAPHICALGRIDSYSTEMS.MAPS',
    'ORTHOIMAGERY.ORTHOPHOTOS',
]

IGN_SERVICE = '&service=WMTS&request=GetTile&version=1.0.0&style=normal&tilematrixset=PM&format=image/jpeg&tilematrix={z}&tilerow={y}&tilecol={x}'
SET_IGN = [
    'http://wxs.ign.fr/'+IGN_KEY+'/geoportail/wmts?layer='+IGN_LAYER[0]+IGN_SERVICE,
    'http://wxs.ign.fr/'+IGN_KEY+'/geoportail/wmts?layer='+IGN_LAYER[1]+IGN_SERVICE,
]

# Attribution generation //IGN, OSM, PGHM
#GEOPORTAIL_ATTRIB = '<a href="http://www.geoportail.fr/" target="_blank">'+'<img src="http://api.ign.fr/geoportail/api/js/latest/'+'theme/geoportal/img/logo_gp.gif"></a>'
IGN_ATTRIB = '<a href="http://www.ign.fr/" target="_blank">'+'<img style="height: 25px; width: 25px;" title="Institut national de l\'information géographique et forestière" src="http://wxs.ign.fr/static/logos/IGN/IGN.gif"></a>'
OSM_ATTRIB = '©'+'<a href="http://www.openstreetmap.org/copyright" target="_blank"> OpenStreetMap</a>'+' contributors'
PGHM_ATTRIB = 'GIS.PGHM | '

SET_ATTRIB = [
    PGHM_ATTRIB+IGN_ATTRIB,
    PGHM_ATTRIB+OSM_ATTRIB,
]

LEAFLET_CONFIG = {
    # conf here
    'DEFAULT_CENTER': (45.2, 5.7),
    'TILES': [
        ('IGN Maps', SET_IGN[0], SET_ATTRIB[0]),
        ('IGN Ortho', SET_IGN[1], SET_ATTRIB[0]),
        ('OSM', 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', SET_ATTRIB[1]),
        #('OrthoMapBox', 'http://{s}.tiles.mapbox.com/v3/openstreetmap.map/{z}/{x}/{y}.jpg', '(c) MapBox'),
    ],
    #'TILES': [],
    #'OVERLAYS': [],
    #'TILES_EXTENT': SPATIAL_EXTENT,
    #'TILES_EXTENT': (-45, 0, 6, 50),
    #'TILES_EXTENT': [924861,6375196,985649,6448688],
    'DEFAULT_ZOOM': 9,
    'MIN_ZOOM': 5,
    'MAX_ZOOM': 17,
    #'ATTRIBUTION_PREFIX': 'Powered by django-leaflet',
    'MINIMAP': True,
    #'SCALE': 'both',
    'RESET_VIEW': True,
}


# Reconfig

#LOGIN_REDIRECT_URL = '/'

TIME_ZONE = 'Europe/Paris'